language: csharp
solution: "Priority Queue VS 2012 Solution.sln"
install:
  - nuget restore "Priority Queue VS 2012 Solution.sln"
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release "Priority Queue VS 2012 Solution.sln"
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyPoject.Tests/bin/Release/MyProject.Tests.dll
